### ISSUE TITLE
Time for the next python-augeas release

### ISSUE THREAD

**Issue by blackduckx** [hercules-team/python-augeas#13]
Hello,

I am eagerly waiting for the fix to use 'None' values for setm to be in a release ...
It would help me to get salt to be able to setup kernel parameters with no key,value scheme in grub.conf as a sample.
Is a 0.5.1 release in the tracks ?

Regards,
Frédéric

**Comment by raphink** [comment]
@giraldeau it seems you crafted the last release. Would you like to do this one?

**Comment by thedrow** [comment]
With https://github.com/hercules-team/python-augeas/pull/14 it's time for a major version release :)
Ping @raphink @giraldeau

**Comment by blackduckx** [comment]
Hello, any news on a release date ?

**Comment by pspacek** [comment]
I second this, a new release would be rellly nice. I would like to get it into Fedora ASAP and use it as well. Thanks!

**Comment by thedrow** [comment]
I was just granted with release privileges. I'll release as soon as I can.

**Comment by rackergs** [comment]
i can update the fedora pkg

**Comment by thedrow** [comment]
@rackergs Please do :)

**Comment by gregswift** [comment]
Out of curiousity... any particular distros we want to release to for Fedora/EL ?  We bumped to 1.0.0 but I think that we should be fine for backwards compat? Please correct me if i'm wrong. I'm gonna just do the fedora ones right now. will follow up with EL based on feedback.

Remotes:
  origin/el6
  origin/epel7
  origin/f24
  origin/f25
  origin/f26

**Comment by thedrow** [comment]
The library is 100% backwards compatible. The reason for the major version bump is because the library was rewritten to use CFFI instead of ctypes.

**Comment by thedrow** [comment]
I guess releasing it to the previously existing repositories is a must. Anything else is a bonus.
