### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by thedrow** [hercules-team/python-augeas#31]
We'd rather support only modern python versions.
For compatibility, users should use an older version. Probably 0.5.

**Comment by hugovk** [comment]
Perhaps only support 2.7 and 3.4+, the others are all EOL:
https://en.wikipedia.org/wiki/CPython#Version_history

I'd also recommend adding classifiers in setup.py, for example:
https://github.com/pypa/pip/blob/master/setup.py
