### ISSUE TITLE
Is the 1.x series now stable enough for me to care to publish it?

### ISSUE THREAD

**Issue by gregswift** [hercules-team/python-augeas#36]
Fedora packager here... I know that i haven't checked in for a while, but the early 1.x broke a lot of ppl so I never pushed it.  Whats the current status?

**Comment by thedrow** [comment]
I need to fix #34 first and release a new version.
I haven't found the time to do so yet.

**Comment by ptoscano** [comment]
> I need to fix #34 first and release a new version.
> I haven't found the time to do so yet.

Hi @thedrow, are there any news about it? See also #42...

**Comment by thedrow** [comment]
Yeh sorry I need to take care of it.

**Comment by ptoscano** [comment]
Friendly ping ;-)

**Comment by ptoscano** [comment]
hi @thedrow , any news about this?

**Comment by thedrow** [comment]
I released 1.1.0 without #34.
I think that for now packaging it is better than having nothing.
