### ISSUE TITLE
Using cffi in in-line vs out-of-line ABI mode

### ISSUE THREAD

**Issue by jefferyto** [hercules-team/python-augeas#48]
I'm helping someone packaging python-augeas for OpenWrt (openwrt/packages#12913).

I noticed that you are [using](https://github.com/hercules-team/python-augeas/blob/dca8493535edd5ae6de788ed9a86c6c05f26fd3f/setup.py#L23) the [Setuptools integration](https://cffi.readthedocs.io/en/latest/cdef.html#distutils-setuptools), which is for [out-of-line ABI](https://cffi.readthedocs.io/en/latest/cdef.html#out-of-line-abi) (or out-of-line API) mode, where a builder script (e.g. foo_build.py) is called during install to produce an output file (_foo.py), and it is the output file that is imported during run-time.

However, you are [importing](https://github.com/hercules-team/python-augeas/blob/dca8493535edd5ae6de788ed9a86c6c05f26fd3f/augeas/__init__.py#L35) the builder file during run-time instead of the output file, which is [in-line ABI](https://cffi.readthedocs.io/en/latest/cdef.html) mode (see the first bullet point after the table of contents).

I can open a PR to fix this, but I would like to ask if you have a preference on which mode to use. Out-of-line is faster to import during run-time though I'm not sure how big of a difference it will be for this library.

**Comment by thedrow** [comment]
Feel free to try to fix this.
