### ISSUE TITLE
Improve feedback of delegated save action rather than throwing IOError with contentless error message

### ISSUE THREAD

**Issue by krichter722** [hercules-team/python-augeas#8]
If `Augeas._libaugeas.aug_save(self.__handle)` fails in `augeas.py`, i.e. returns with a non-zero code, an IOError is raised and a contentless error message is thrown. I'm not too familiar with the c bindings for python, but I guess error handling can be improved and the cause for the failure provided.

**Comment by tomislacker** [comment]
+1
At least something to differentiate something like a permissions problem versus lens violation.
